### ISSUE TITLE
Buffers in marlin setting

### ISSUE THREAD

**Issue by yaldashbz** [ModelCloud/GPTQModel#102]
Hi,

I want to access qweights and qzeros in marlin QuantLinear, like QuantLinear in exllamav2, to be able to dequantize it with [this](https://github.com/ModelCloud/GPTQModel/blob/main/gptqmodel/nn_modules/qlinear/qlinear_marlin.py) function in qlinear_marlin.py. Could you please guide me on how to access these buffers in the marlin setting? How are they stored in the B buffer?

Thanks.

**Comment by Qubitium** [comment]
After loading with `.from_quantized` you can loop over all the `model.named modules` and check if layer/module `isinstance(module, qlinear_marlin)` and access all the 4bit weights, qzeros weights, and scale weights. Is this what you are asking?

**Comment by yaldashbz** [comment]
@Qubitium Thanks, but the `QuantLinear` module in the qlinear_marlin only has a `B` buffer and `s`. I don't understand what is the `B` buffer and how to extract the qweights and qzeros from it to use `dequantize_weight` in the https://github.com/ModelCloud/GPTQModel/blob/main/gptqmodel/nn_modules/qlinear/qlinear_marlin.py#L220C5-L220C22

**Comment by Qubitium** [comment]
Ok. I see. You are right, the .B holds the qweights for Marlin and you have to do a lot of reversal to get back the original. But the code is there so you can try and reverse each setup. 

```py
        w = linear.weight.data.t() 
        if self.group_size != self.infeatures:
            w = w.reshape((-1, self.group_size, self.outfeatures))
            w = w.permute(1, 0, 2)
            w = w.reshape((self.group_size, -1))
            s = s.reshape((1, -1))
        w = torch.round(w / s).int()
        w += (maxq + 1) // 2
        w = torch.clamp(w, 0, maxq)
        if self.group_size != self.infeatures:
            w = w.reshape((self.group_size, -1, self.outfeatures))
            w = w.permute(1, 0, 2)
            w = w.reshape((self.infeatures, self.outfeatures)).contiguous()
            s = s.reshape((-1, len(_scale_perm)))[:, _scale_perm]
        else:
            s = s.reshape((-1, len(_scale_perm_single)))[:, _scale_perm_single]
        s = s.reshape((-1, self.outfeatures)).contiguous()
        w = w.reshape((self.infeatures // tile, tile, self.outfeatures // tile, tile))
        w = w.permute((0, 2, 1, 3))
        w = w.reshape((self.infeatures // tile, self.outfeatures * tile))
        res = w
        res = res.reshape((-1, _perm.numel()))[:, _perm].reshape(res.shape)
        q = np.zeros((res.shape[0], res.shape[1] // 8), dtype=np.uint32)
        res = res.cpu().numpy().astype(np.uint32)
        for i in range(8):
            q |= res[:, i::8] << 4 * i
        q = torch.from_numpy(q.astype(np.int32)).to(w.device)
        self.B[:, :] = q.to(self.B.device) <---------- .B
```
