### ISSUE TITLE
[BUG] saving problem for larger model which require shard checkpoints

### ISSUE THREAD

**Issue by ChenMnZ** [ModelCloud/GPTQModel#253]
Hi,

I think this bug is similar to https://github.com/ModelCloud/GPTQModel/issues/252.

I found that the following code can load any GPTQ v2 models successfully:
```
model = GPTQModel.from_quantized(args.model, device_map='auto',torch_dtype=torch.float16)
```
However, when I try to saving like：
```
model.save_pretrained(args.save_dir)  
```
I found that no any checkpoints is saved. Additionally, if I try to save as:
```
model.model.save_pretrained(args.save_dir)  
``` 
The shard checkpoints can be saving. However, the output results of model are wrong when reload the saved checkpoints throug `model.model.save_pretrained`.

Overall, `model.save_pretrained` cannot save shard checkpoints. `model.model.save_pretrained` can save shard checkpoints while produce wrong outputs.

**Comment by Qubitium** [comment]
@ChenMnZ We will check to see the save_pretrained is incorrectly overridded by GPTQModel. Can you also test directly using `.save_quantized()` viat the sharded unit sample/test here

https://github.com/ModelCloud/GPTQModel/blob/main/tests/test_sharded.py#L88-L91

**Comment by Qubitium** [comment]
fixed in pr #259

**Comment by Qubitium** [comment]
We have reverted PR #259 in https://github.com/ModelCloud/GPTQModel/pull/277 . We will use a more compatible fix in new PR.

**Comment by Qubitium** [comment]
fixed in Pr 296.
