### ISSUE TITLE
[FEATURE] Add `GPTQModel.shard_quantized()` api for re-sharding previously quantized model

### ISSUE THREAD

**Issue by ChenMnZ** [ModelCloud/GPTQModel#264]
The exllama v2 backeend can inference correctly. However, I find that it has some bugs about saving model.
For example, leveraging `exllama v2` and `Triton` to load a same model respectively:
```python
# origin model produce correct output
model = GPTQModel.from_quantized(args.model, device_map='auto',torch_dtype=torch.float16, backend=get_backend('EXLLAMA_V2'))
model.save_quantized(args.save_dir,max_shard_size='8GB')  

# saved model produce wrong output
model2 = GPTQModel.from_quantized(args.save_dir, device_map='auto',torch_dtype=torch.float16, backend=get_backend('EXLLAMA_V2'))
```

```python
# origin model produce correct output
model = GPTQModel.from_quantized(args.model, device_map='auto',torch_dtype=torch.float16, backend=get_backend('TRITON'))
model.save_quantized(args.save_dir,max_shard_size='8GB')  


# saved model produce correct output
model2 = GPTQModel.from_quantized(args.save_dir, device_map='auto',torch_dtype=torch.float16, backend=get_backend('EXLLAMA_V2'))
```

We can find that both of the model can obtain correct output and see the corresponding quantized models in `args.save_dir`. However, if we reload the saved model in `args.save_dir`, we can observe that the model saved by `EXLLAMA_V2` produce wrong output.

I have displayed the saved weight, and find that the model weights with `EXLLAMA_V2` backend are changed abnormally after calling `save_quantized`.

Additionally, I only test checkpoints with GPTQ v2 format.

**Comment by Qubitium** [comment]
@ChenMnZ  Based on your code, you are trying to "shard" a already-quantized model correct? We never tested this code path and we will add a unit test to either disable this or fix this situation of sharding an already quantized model.

**Comment by ChenMnZ** [comment]
I found this bug accidently. This bug wound still exits when replace
```
model.save_quantized(args.save_dir,max_shard_size='8GB') 
```
with
```
model.save_quantized(args.save_dir,max_shard_size='8GB') 
```

**Comment by Qubitium** [comment]
@ChenMnZ  Confirmed this bug. The code path should be disabled. We will not allow `save_quantized()` to be called on a post-quantized model. This introduces lots of bugs that is quite impossible to fix with existing api without bloating up the code with messy logic.

We will add a new `GPTQModel.shard_quantized(quantized_model_path_or_id, shard_size, output_dir)` api for users that want to re-shard a previously quantized model.

**Comment by Qubitium** [comment]
Completed by PR #271. Please use `GPTQModel.shard_quantized()` for re-sharding a model that is already quantized and saved to disk.
