### ISSUE TITLE
[BUG] Build fails on Manjaro/Arch Linux

### ISSUE THREAD

**Issue by KnutJaegersberg** [ModelCloud/GPTQModel#351]
**Describe the bug**

Building GPTQModel on Manjaro fails. I have the suspicion it is because of Arch Linux, from my research, I think the error means I should try to build with gcc-12 and g++-12 but switching to those with variable export didn't work. 
I guess the problem will disappear if you have a pip version. 

Part of the exceptions:

Emitting ninja build file /run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/3] /opt/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/gptqmodel_ext/marlin/marlin_cuda_kernel.o'.d -I/home/knut/transformers/lib/python3.9/site-packages/torch/include -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/TH -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include '-I/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/gptqmodel_cuda' -I/home/knut/transformers/lib/python3.9/site-packages/nvidia/cuda_runtime/include -I/home/knut/transformers/include -I/usr/include/python3.9 -c -c '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/gptqmodel_ext/marlin/marlin_cuda_kernel.cu' -o '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/gptqmodel_ext/marlin/marlin_cuda_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 --threads 2 -Xfatbin -compress-all -diag-suppress=179,39 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=gptqmodel_marlin_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -ccbin g++
  FAILED: /run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/gptqmodel_ext/marlin/marlin_cuda_kernel.o
  /opt/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/gptqmodel_ext/marlin/marlin_cuda_kernel.o'.d -I/home/knut/transformers/lib/python3.9/site-packages/torch/include -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/TH -I/home/knut/transformers/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include '-I/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/gptqmodel_cuda' -I/home/knut/transformers/lib/python3.9/site-packages/nvidia/cuda_runtime/include -I/home/knut/transformers/include -I/usr/include/python3.9 -c -c '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/gptqmodel_ext/marlin/marlin_cuda_kernel.cu' -o '/run/media/knut/HD/huggingface models/language models/LLMs/GPTQModel/build/temp.linux-x86_64-cpython-39/gptqmodel_ext/marlin/marlin_cuda_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 --threads 2 -Xfatbin -compress-all -diag-suppress=179,39 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=gptqmodel_marlin_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -ccbin g++
  /usr/include/c++/14.1.1/x86_64-pc-linux-gnu/bits/c++config.h(827): error: user-defined literal operator not found
      typedef __decltype(0.0bf16) __bfloat16_t;
                         ^

  /usr/include/stdlib.h(141): error: identifier "_Float32" is undefined
    extern _Float32 strtof32 (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(147): error: identifier "_Float64" is undefined
    extern _Float64 strtof64 (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(153): error: identifier "_Float128" is undefined
    extern _Float128 strtof128 (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(159): error: identifier "_Float32x" is undefined
    extern _Float32x strtof32x (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(165): error: identifier "_Float64x" is undefined
    extern _Float64x strtof64x (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(299): error: identifier "_Float32" is undefined
             _Float32 __f)
             ^

  /usr/include/stdlib.h(305): error: identifier "_Float64" is undefined
             _Float64 __f)
             ^

  /usr/include/stdlib.h(311): error: identifier "_Float128" is undefined
       _Float128 __f)
       ^

  /usr/include/stdlib.h(317): error: identifier "_Float32x" is undefined
       _Float32x __f)
       ^

  /usr/include/stdlib.h(323): error: identifier "_Float64x" is undefined
       _Float64x __f)
       ^

  /usr/include/stdlib.h(436): error: identifier "_Float32" is undefined
    extern _Float32 strtof32_l (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(443): error: identifier "_Float64" is undefined
    extern _Float64 strtof64_l (const char *__restrict __nptr,
           ^

  /usr/include/stdlib.h(450): error: identifier "_Float128" is undefined
    extern _Float128 strtof128_l (const char *__restrict __nptr,
           ^

**Comment by Qubitium** [comment]
@KnutJaegersberg  Can you test upgrading python from 3.9 to 3.10 or 3.11?  Or use conda to create a virtual python env with python 3.10/3.11. I want to see if the error is caused by python or your g++.

**Comment by KnutJaegersberg** [comment]
I tried 3.11 in a virtualenv but I get the same error. so that means it's likely g++? I tried version 11,12, 13. I'd guess I'm supposed to use 12 on my system, given my cuda version.

**Comment by Qubitium** [comment]
setup.py has c++ 17 flag so maybe you need to have 17 installed.

**Comment by Qubitium** [comment]
For reference our ci and dev env is based of Ubuntu 22.04 and any dev/compiler. 

I would recommend upgrading your compiler to something similar to Ubuntu 22.04 or use a container system such lxd or docker to compile without having to touch your base is which can be a pain to reconfigure.

**Comment by KnutJaegersberg** [comment]
ok thanks.

**Comment by KnutJaegersberg** [comment]
on the sporadic attempts I've undertaken, i've not been able to build gptqmodel on my PC. as far as I know, I'm using the right gcc version. this keeps me from adopting your tool.

**Comment by KnutJaegersberg** [comment]
I mean I could indeed use a container, but I haven't bothered - I just want to install this the regular way.

**Comment by Qubitium** [comment]
Is Manjaro officially supported by Nvidia for cuda toolkit? Nvidia is has very tight (strict) integration of their driver/cuda combo. 

Also, launching an official Nvidia docker image is only one line of code.

We do not have the resources to debug arch or other distros that is not nvidia sanctioned.

**Comment by KnutJaegersberg** [comment]
got that, I'll use the image
