### ISSUE TITLE
[Feature Request] separate kernel in another repo

### ISSUE THREAD

**Issue by wenhuach21** [ModelCloud/GPTQModel#384]
We plan to use your repository to support the CUDA kernel. However, since the GPTQModel already imports auto-round, integrating this is proving to be quite challenging. Could you consider separating the kernel component into a separate repository? This would greatly facilitate our integration efforts. Thank you!

**Comment by Qubitium** [comment]
@wenhuach21  Sorry for the late reply. Our workload is currently prohibitive at the moment at doing this but I will get this resolved as fast as we can manage. We should have this resolved next week.

**Comment by wenhuach21** [comment]
Thank you. We plan to initiate a code freeze around September 15th for the upcoming release. It would be ideal if we could integrate your repository into the new version

**Comment by wenhuach21** [comment]
Thanks, but it seems that the pip install is a little slow
