### ISSUE TITLE
[QA]Could you share the dequantization algorithm for GPTQ format model

### ISSUE THREAD

**Issue by sunzj** [ModelCloud/GPTQModel#437]
RT.
Is there any python code of dequantization  algorithm. i found http://eadst.com/blog/220, i am not sure it's right or not.

For example, there are w2g64 weights.
q_weight  [256, 4 096]
q_scale     [64, 256]
q_zero      [64, 4 096]

the dequant weigth is [4096, 4096], how to get it?

**Comment by Qubitium** [comment]
Is this 2bit model quanted by gptqmodel?

**Comment by sunzj** [comment]
> Is this 2bit model quanted by gptqmodel?

No, it transfer from other format. Actully, it's https://huggingface.co/ChenMnZ/Llama-3-8b-instruct-EfficientQAT-w2g64-GPTQ/tree/main

as it's said, this model is "transfer EfficientQAT quantized models into GPTQ v2 format"

**Comment by Qubitium** [comment]
Are you trying to reverse quantization from 2bit back to fp16 and save the model as native fp16?

**Comment by sunzj** [comment]
> Are you trying to reverse quantization from 2bit back to fp16 and save the model as native fp16?

no, i just implement model inference. 

anyway, after check the quantize algorithm, i success dequant the weight.
