### ISSUE TITLE
[BUG] examples/benchmark/perplexity.py, raise error

### ISSUE THREAD

**Issue by simplew2011** [ModelCloud/GPTQModel#504]
```
gptqmodel==1.1.0
transformers==4.46.1
tokenizers== 0.20.1
torch==2.5.1
NVIDIA H800
```

- test source model [Qwen2.5-7B-Instruct](https://hf-mirror.com/Qwen/Qwen2.5-7B-Instruct) perplexity
- CUDA_VISIBLE_DEVICES=0 python examples/benchmark/perplexity.py
- model forward output parse `outputs.logits.detach()` error

```

Traceback (most recent call last):
  File "/home/wzp/code/GPTQModel/examples/benchmark/perplexity.py", line 109, in <module>
    ppl.calculate(args.n_ctx, args.n_batch)
  File "/home/wzp/code/GPTQModel/gptqmodel/utils/perplexity.py", line 125, in calculate
    nll, count = self._process_batch(i, n_ctx, n_batch, tokens, nll, count)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzp/code/GPTQModel/gptqmodel/utils/perplexity.py", line 180, in _process_batch
    batch_logits = self._compute_batch_logits(tokens, batch_start, batch_size)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzp/code/GPTQModel/gptqmodel/utils/perplexity.py", line 227, in _compute_batch_logits
    return outputs.logits.detach()
           ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'logits'
```

![image](https://github.com/user-attachments/assets/3f396491-2bea-4959-86c1-2f3dc6d2e096)

**Comment by Qubitium** [comment]
@simplew2011 Thank you for the report. We are checking this now.

**Comment by Qubitium** [comment]
@simplew2011 Are you running the code on a quantized model or native model?

**Comment by PZS-ModelCloud** [comment]
@simplew2011 
Can't reproduce your bug in my env. 

transformers==4.46.1
tokenizers== 0.20.1
torch==2.5.1
```
 CUDA_VISIBLE_DEVICES=0 python examples/benchmark/perplexity.py
```

![截屏2024-10-30 17 52 55](https://github.com/user-attachments/assets/ef2a6a2b-11f7-45c0-bb5e-f1cc259e4827)

![截屏2024-10-30 17 51 40](https://github.com/user-attachments/assets/d8e60685-8864-446a-bd1f-012c02ded2a8)

**Comment by simplew2011** [comment]
- perhaps the --backend selected is difference
- when run `python examples/benchmark/generation_speed.py  --backend AUTO`, info show:
    - [importer.py:55] Auto choose the fastest one based on quant model compatibility: <class 'gptqmodel.nn_modules.qlinear.qlinear_tritonv2.TritonV2QuantLinear'>

**Comment by simplew2011** [comment]
@PZS-ModelCloud can you set `--backend` to one of 'TRITON', 'EXLLAMA', 'EXLLAMA_V2', test and see

**Comment by Qubitium** [comment]
Please let us know the exact cmd/cli that triggered your error with torch and transformer version

**Comment by simplew2011** [comment]
`CUDA_VISIBLE_DEVICES=0 python examples/benchmark/perplexity.py --model_name path/to/Qwen2.5-7B-Instruct --backend AUTO`

```
gptqmodel==1.1.0
transformers==4.46.1
tokenizers== 0.20.1
torch==2.5.1
NVIDIA H800
```

**Comment by Qubitium** [comment]
@simplew2011 We tried multiple backends using your exact cli with no error. 

![image](https://github.com/user-attachments/assets/7c09e1a6-7c66-4a96-a87f-4feb96fddcf3)

**Comment by Qubitium** [comment]
Note that `backend` has no effect here because the model is not quantized and is native bf16/fp16.
