### ISSUE TITLE
[COMPAT] Windows WSL support

### ISSUE THREAD

**Issue by Nojahhh** [ModelCloud/GPTQModel#757]
Hi, thank you for your great work so far. Following your updates closely and I'm hoping for windows support soon!
Is that somehting you have planned for in the future?

**Comment by Qubitium** [comment]
@CSY-ModelCloud  Assigned to investigate and integrate Window WSL support.

**Comment by Qubitium** [comment]
@Nojahhh  Any update on your end?

**Comment by Qubitium** [comment]
Closing issue as there have been no response from user. Please re-open ticket if you can detail what windows env you expect to run gptqmodel under. @Nojahhh
