### ISSUE TITLE
[CORE] Multi-Modal Calibration

### ISSUE THREAD

**Issue by Qubitium** [ModelCloud/GPTQModel#863]
Currently visual layers in VL models are skipped. We need to add image calibration. 

Tracking PR: https://github.com/ModelCloud/GPTQModel/pull/685

**Comment by Qubitium** [comment]
Ovis PR ready but need a coherent structure for all image to text hybrid models so that both Qwen2-VL and Ovis can use same api for model loading and dataset quantization

**Comment by bhavyajoshi-mahindra** [comment]
If these any update on how to prepare calibration dataset for Qwen2-VL gptq quantization?

**Comment by Qubitium** [comment]
@bhavyajoshi-mahindra The current image based calibration is to help to correctly quantize the text-layers (which are hybrid layers) for image to text generation. We need to do more research to ensure proper quantization of the image model layers.

**Comment by bhavyajoshi-mahindra** [comment]
I am trying to again quantize my custom qwen2-vl model. What would be a correct dataset calibration format?
The example that is mentioned in readme of gptqmodel actually passes the tokenized content to quantized the model.
I tried the same but I got the type error 

```
Traceback (most recent call last):
  File "/home/bhavya/Desktop/bhavya/llm/gptqmodel/qwen2_vl_gptq_quantize1.py", line 42, in <module>
    model.quantize(calibration_dataset)
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/base.py", line 284, in quantize
    calibration_dataset = self.prepare_dataset(calibration_dataset, batch_size, tokenizer,)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/definitions/qwen2_vl.py", line 106, in prepare_dataset
    image_inputs = self.process_vision_info(batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/definitions/qwen2_vl.py", line 67, in process_vision_info
    vision_infos = extract_vision_info(conversations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/utils/image.py", line 13, in extract_vision_info
    if isinstance(message["content"], list):
                  ~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by bhavyajoshi-mahindra** [comment]
got it thanks, although I had to make some code changed inside gptqmodel.

**Comment by Qubitium** [comment]
What code changes do you have to make?

**Comment by bhavyajoshi-mahindra** [comment]
It is suggested to pass **tokenized text** as calibration data as mentioned in the example  in readme of gptqmodel (i know its was not meant for qwen2-vl). But it seems that the expected caliber data format is a **list of message['content']** as mentioned in line 13 of "gptqmodel/utils/image.py". So I made some changes in the same file to support my input data caliber format which is something like 

```
[
    {
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": "/path/to/image1.jpg"},
                    {"type": "text", "text": "Example text 1"}
                ]
            }
        ]
    },
    {
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": "/path/to/image2.jpg"},
                    {"type": "text", "text": "Example text 2"}
                ]
            }
        ]
    }
]
```

so I changed the line 13 and 14 of same code to
```
if isinstance(['messages'][0]['content'], list):
    for ele in ['messages'][0]['content']:
```


I hope this makes sense.

**Comment by bhavyajoshi-mahindra** [comment]
@Qubitium  Any update of quantization of image model layers of the qwen2-vl model?

**Comment by Qubitium** [comment]
We have no plans to quantize image layers as they are relatively small and potential for error loss isuch greater than text-hybrid layers.

**Comment by bhavyajoshi-mahindra** [comment]
so can we expect similar accuracy after quantization as of now? and also, is the correct the way I passed calibration data for quantization?
