### ISSUE TITLE
[BUG] Dynamic Skip Layers get wrong output

### ISSUE THREAD

**Issue by HaoWuSR** [ModelCloud/GPTQModel#905]
**Describe the bug**

When I use GPTQModel to quantize Tiny-llama-1.1b with following quantize_config.json, the generated text is  
<img width="690" alt="Clipboard_Screenshot_1734513731" src="https://github.com/user-attachments/assets/71514878-7da7-46de-9176-8a170aaa9330" />

```
dynamic = {
  r"-:.*\.(?:[1-9]|1[0-9]|2[0-1])\..*": {},
}
```

And I print the keys and param values from the quantized ckpt, the value and groupsize is error. 

```
Parameter: model.model.layers.21.self_attn.o_proj.qweight
param: Parameter containing:
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.int32)
Shape: torch.Size([128, 4096])
Data type: torch.int32

Parameter: model.model.layers.21.self_attn.o_proj.g_idx
param: Parameter containing:
tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0', dtype=torch.int32)
Shape: torch.Size([2048])
Data type: torch.int32
```

Do you have a ckpt quantized by skipping some layers? 

**GPU Info**

A10

**Software Info**

Operation System/Version + Python Version

Show output of:
```
pip show gptqmodel torch transformers accelerate triton
```

**If you are reporting an inference bug of a post-quantized model, please post the content of `config.json` and `quantize_config.json`.**

**To Reproduce**

How to reproduce this bug if possible.

**Expected behavior**

Inference successfully 

**Model/Datasets**

Make sure your model/dataset is downloadable (on HF for example) so we can reproduce your issue.

**Screenshots**

**Additional context**

**Comment by Qubitium** [comment]
@HaoWuSR Confirmed. Fix coming asap.

**Comment by ZX-ModelCloud** [comment]
This issue resolved. see [PR#907](https://github.com/ModelCloud/GPTQModel/pull/907)

**Comment by HaoWuSR** [comment]
Thanks for your help! 
I've noticed an interesting phenomenon: After quantizing the Tiny-1.1B model and skipping all layers, the saved checkpoint is only 2GB, which is half the size of the 4GB FP16 weights. Upon comparison, I found that the weight values are identical in both versions (BF16 and FP16). This doesn't seem to be related to packing. I'm curious about what could be causing this size difference?
```
dynamic = {
  r"-:.*\.(?:[0-9]|1[0-9]|2[0-1])\..*": {}, 
}
```

**Comment by Qubitium** [comment]
> Thanks for your help! I've noticed an interesting phenomenon: After quantizing the Tiny-1.1B model and skipping all layers, the saved checkpoint is only 2GB, which is half the size of the 4GB FP16 weights. Upon comparison, I found that the weight values are identical in both versions (BF16 and FP16). This doesn't seem to be related to packing. I'm curious about what could be causing this size difference?

Are you sure the original model is not saved as FP32? This would explain 2x size reduction when you call save. 

We don't have a magic compression code for FP16/BF16. =P I wish we did.

**Comment by HaoWuSR** [comment]
Thank you for your reply! 
I've double-checked and confirmed that the original checkpoint was indeed saved in fp32 format. I sincerely apologize for the confusion 🤣
