### ISSUE TITLE
[FEATURE] Intel/AutoRound Integration

### ISSUE THREAD

**Issue by Qubitium** [ModelCloud/GPTQModel#93]
Integrade Intel/AutoRound pkg/api into GPTQModel:

1. Allow Intel/AutoRound quantization (much slower but result in higher quality quants)
2. Allow `lm_head` layer/module quantization. Complete todo. `lm_head` quantized inference is already merged into main.

Target: v0.9.2

**Comment by Qubitium** [comment]
Milestone target changed to v0.9.3

**Comment by wenhuach21** [comment]
For the speed issue, could you let me know which GPU you are using? Please set low_gpu_mem_usage to False. This should result in a 50%-100% speedup based on my experience. If GPU memory is insufficient, set nsamples to 128, which will cause only a slight drop in accuracy.

BTW, we are changing the default value to this after extensive test.
