### ISSUE TITLE
[FEATURE] Intel/Habana HPU Support

### ISSUE THREAD

**Issue by Qubitium** [ModelCloud/GPTQModel#94]
Integrate intel/Habana HPU kernel support for uint4 inference on Habana HPU. This was merged into AutoGPTQ https://github.com/AutoGPTQ/AutoGPTQ/pull/689/files but there are no ci tests and we have no access to habana hpu to even test this.

For this to work. We need:

1. Consistent access to habana HPU for ci testing/regression testing on all future releases. We will not merge any feature we cannot regression test against commits. 
2. Create CI test to ensure the code works with valid PPL pre/post quantization on Habana HPU.

@HolyFalafel As the creator of the AutoGPTQ PR for habana HPU integration, do you know how or where to get developer access to Habana HPU for testing? Do you have contacts at Intel to allow us to get some credits for future regression testing. Without consistent access to Habana HPU, we will not even attempt to merge this feature since we will only merge that we can vouch and regression test for all future changes.  Thanks!

**Comment by HolyFalafel** [comment]
@Qubitium, I've forwarded it to relevant people in Habana.
They'll reply soon

**Comment by Qubitium** [comment]
@HolyFalafel I did not get any feedback on this from your contact. Can you tell me when or which email domain did they use? Thanks

My contact is qubitium@modelcloud.ai and x handle @qubitium. We are willing spend to keep gptqmodel +  in sync habana support as long we can consistently run unit tests for tinyllama model that we like to use since llama structured model is dominant.

**Comment by Qubitium** [comment]
We are ramping for gptqmod 1.1 major release this weekend and want to slot in intel hpu support if possible. We can do the cherrypick from autogptq and merge and just need a small instance to run ci for aforementioned tinyllama 4bit inferenence
